## Point Selection

Importing Python libraries:

In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import ipywidgets as widgets

Reading image:

In [2]:
# fig = plt.figure(figsize=(50,70))
image = cv2.imread('balloonfiesta.jpeg')
resized_image = cv2.resize(image, (800,500))
circles = np.zeros((4,2), int)
counter = 0

Function for detecting clicks on image and putting them in circle matrix:

In [3]:
def detectPoints(event,x,y,flags,params):
    global counter
    if event == cv2.EVENT_LBUTTONDOWN:
        circles[counter] = x,y
        counter = counter + 1
        print(circles)
        
# cid = fig.canvas.mpl_connect('button_press_event', detectPoints)

# imgplot = plt.imshow(image)
# plt.show()

Perform Template Matching once 4 points has been detected:

In [ ]:
while True:
    if counter == 4:
        width, height = 250,350
        pts1 = np.float32([circles[0],circles[1],circles[2],circles[3]])
        pts2 = np.float32([[0,0], [width,0], [0,height], [width,height]])
        matrix = cv2.getPerspectiveTransform(pts1,pts2)
        imgOutput = cv2.warpPerspective(resized_image,matrix,(width,height))
        cv2.imshow("Output Image", imgOutput)
        
    for x in range(0,4):
        cv2.circle(resized_image,(circles[x][0], circles[x][1]),3,(0,255,0),cv2.FILLED)
        
    cv2.imshow("Original", resized_image)
    cv2.setMouseCallback("Original", detectPoints)
    cv2.waitKey(1)

[[157  47]
 [  0   0]
 [  0   0]
 [  0   0]]
[[157  47]
 [215  47]
 [  0   0]
 [  0   0]]
[[157  47]
 [215  47]
 [159 100]
 [  0   0]]
[[157  47]
 [215  47]
 [159 100]
 [215  98]]
